# Generated by Django 4.1.2 on 2022-10-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_co_autor_alter_livro_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
