# Generated by Django 4.1.2 on 2022-10-05 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
